A script to extract EMIT reflectance to points

In [6]:
# Import Packages
import sys
import os
import numpy as np
import pandas as pd
import holoviews as hv
import pandas as pd

# Import Packages
import earthaccess

import xarray as xr
import hvplot.pandas
import hvplot.xarray

#sys.path.append('../')
sys.path.append('EMIT-Data-Resources/python/modules/')

from emit_tools import emit_xarray

Getting the working directory to inform the user

In [2]:
os.getcwd()

'C:\\Users\\campb\\Documents'

In [3]:
earthaccess.login(persist=True)

In [20]:

url = 'https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/EMITL2ARFL.001/EMIT_L2A_RFL_001_20260125T172705_2602511_009/EMIT_L2A_RFL_001_20260125T172705_2602511_009.nc'
##Panama cifuentes https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/EMITL2ARFL.001/EMIT_L2A_RFL_001_20250523T182128_2514312_003/EMIT_L2A_RFL_001_20250523T182128_2514312_003.nc

In [21]:
# Get requests https Session using Earthdata Login Info
fs = earthaccess.get_requests_https_session()
# Retrieve granule asset ID from URL (to maintain existing naming convention)
granule_asset_id = url.split('/')[-1]
# Define Local Filepath
fp = f'C:/Users/campb/Documents/{granule_asset_id}'
# Download the Granule Asset if it doesn't exist
if not os.path.isfile(fp):
    with fs.get(url,stream=True) as src:
        with open(fp,'wb') as dst:
            for chunk in src.iter_content(chunk_size=64*1024*1024):
                dst.write(chunk)

In [23]:
ds = emit_xarray(fp, ortho=True)
ds

<xarray.Dataset> Size: 4GB
Dimensions:           (latitude: 1884, longitude: 1990, wavelengths: 285)
Coordinates:
  * latitude          (latitude) float64 15kB 17.84 17.84 17.84 ... 16.82 16.82
  * longitude         (longitude) float64 16kB -88.49 -88.48 ... -87.41 -87.41
    elev              (latitude, longitude) float32 15MB nan nan nan ... nan nan
  * wavelengths       (wavelengths) float32 1kB 380.9 388.3 ... 2.493e+03
    fwhm              (wavelengths) float32 1kB ...
    good_wavelengths  (wavelengths) float32 1kB ...
    spatial_ref       int32 4B 0
Data variables:
    reflectance       (latitude, longitude, wavelengths) float32 4GB nan ... nan
Attributes: (12/39)
    ncei_template_version:             NCEI_NetCDF_Swath_Template_v2.0
    summary:                           The Earth Surface Mineral Dust Source ...
    keywords:                          Imaging Spectroscopy, minerals, EMIT, ...
    Conventions:                       CF-1.63
    sensor:                            EMIT (Earth Surface Mineral Dust Sourc...
    instrument:                        EMIT
    ...                                ...
    spatial_ref:                       GEOGCS["WGS 84",DATUM["WGS_1984",SPHER...
    geotransform:                      [-8.84855745e+01  5.42232520e-04 -0.00...
    day_night_flag:                    Day
    title:                             EMIT L2A Estimated Surface Reflectance...
    granule_id:                        EMIT_L2A_RFL_001_20260125T172705_26025...
    Orthorectified:                    True

In [7]:
ds.latitude.max()

<xarray.DataArray 'latitude' ()> Size: 8B
array(17.83614388)
Coordinates:
    spatial_ref  int32 4B 0
Attributes:
    long_name:  Latitude (WGS-84)
    units:      degrees north

In [8]:
ds.latitude.min()

<xarray.DataArray 'latitude' ()> Size: 8B
array(16.81512005)
Coordinates:
    spatial_ref  int32 4B 0
Attributes:
    long_name:  Latitude (WGS-84)
    units:      degrees north

In [9]:
ds.longitude.max()

<xarray.DataArray 'longitude' ()> Size: 8B
array(-87.40680289)
Coordinates:
    spatial_ref  int32 4B 0
Attributes:
    long_name:  Longitude (WGS-84)
    units:      degrees east

In [10]:
ds.longitude.min()

<xarray.DataArray 'longitude' ()> Size: 8B
array(-88.48530337)
Coordinates:
    spatial_ref  int32 4B 0
Attributes:
    long_name:  Longitude (WGS-84)
    units:      degrees east

In [26]:
points = pd.read_csv('C:/Users/campb/Downloads/Morrissette_et_al_2023_plots.csv')
points

,Id,study_id,site_id,plot_id,year,month,day,latitude,longitude,position_method,...,plot_soil_carbon_100cm,plot_plant_carbon,salinity_class,salinity_method,vegetation_class,plot_shape,coordinates_obscured_flag,field_or_manipulation_code,plant_plot_detail_present,soil_core_present
0,1,Morrissette_et_al_2023,Hicks Caye,Hicks Caye_1_1,2021,9,2,17.691465,-88.115920,handheld,...,410.468143,111.371424,brine,measurement,forested,circular,not obscured,field,True,True
1,2,Morrissette_et_al_2023,Hicks Caye,Hicks Caye_1_2,2021,9,2,17.691475,-88.116119,handheld,...,279.044580,64.248500,mixoeuhaline,measurement,forested,circular,not obscured,field,True,True
2,3,Morrissette_et_al_2023,Hicks Caye,Hicks Caye_1_3,2021,9,2,17.691509,-88.116355,handheld,...,453.093397,96.900570,mixoeuhaline,measurement,forested,circular,not obscured,field,True,True
3,4,Morrissette_et_al_2023,Hicks Caye,Hicks Caye_1_4,2021,9,2,17.691458,-88.116596,handheld,...,385.075975,55.686537,mixoeuhaline,measurement,forested,circular,not obscured,field,True,True
4,5,Morrissette_et_al_2023,Hicks Caye,Hicks Caye_1_5,2021,9,2,17.691358,-88.116795,handheld,...,360.208198,23.181276,mixoeuhaline,measurement,forested,circular,not obscured,field,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,109,Morrissette_et_al_2023,Turneffe Atoll,Turneffe Atoll_2_4,2022,3,11,17.285760,-87.812320,handheld,...,569.586838,79.909985,saline,measurement,forested,circular,not obscured,field,True,True
109,110,Morrissette_et_al_2023,Turneffe Atoll,Turneffe Atoll_2_5,2022,3,11,17.285560,-87.812330,handheld,...,505.659014,81.038954,mixoeuhaline,measurement,forested,circular,not obscured,field,True,True
110,111,Morrissette_et_al_2023,Turneffe Atoll,Turneffe Atoll_2_6,2022,3,11,17.285340,-87.812300,handheld,...,588.046910,97.072299,mixoeuhaline,measurement,forested,circular,not obscured,field,True,True
111,112,Morrissette_et_al_2023,Channel Caye,Channel Caye_S_1,2021,9,10,16.644835,-88.164550,handheld,...,NaN,NaN,mixoeuhaline,measurement,seagrass,circular,not obscured,field,True,True
112,113,Morrissette_et_al_2023,Channel Caye,Channel Caye_S_2,2021,9,10,16.644791,-88.164332,handheld,...,NaN,NaN,mixoeuhaline,measurement,seagrass,circular,not obscured,field,True,True

In [27]:
#ds.sel(wavelengths=850,method='nearest').hvplot.image(cmap='greys', frame_height=600, frame_width=600, geo=True, crs='EPSG:4326').opts(title=f"Example Points")*\
#points.hvplot.points(x='longitude',y='latitude', by='Id', color=hv.Cycle('Dark2'), geo=True, crs='EPSG:4326')

In [28]:
points = points.set_index(['Id'])

In [29]:
xp = points.to_xarray()
xp

<xarray.Dataset> Size: 26kB
Dimensions:                     (Id: 113)
Coordinates:
  * Id                          (Id) int64 904B 1 2 3 4 5 ... 110 111 112 113
Data variables: (12/30)
    study_id                    (Id) object 904B 'Morrissette_et_al_2023' ......
    site_id                     (Id) object 904B 'Hicks Caye' ... 'Channel Caye'
    plot_id                     (Id) object 904B 'Hicks Caye_1_1' ... 'Channe...
    year                        (Id) int64 904B 2021 2021 2021 ... 2021 2021
    month                       (Id) int64 904B 9 9 9 9 9 9 9 ... 3 3 3 3 3 9 9
    day                         (Id) int64 904B 2 2 2 2 2 2 ... 11 11 11 10 10
    ...                          ...
    vegetation_class            (Id) object 904B 'forested' ... 'seagrass'
    plot_shape                  (Id) object 904B 'circular' ... 'circular'
    coordinates_obscured_flag   (Id) object 904B 'not obscured' ... 'not obsc...
    field_or_manipulation_code  (Id) object 904B 'field' 'field' ... 'field'
    plant_plot_detail_present   (Id) bool 113B True True True ... True True True
    soil_core_present           (Id) bool 113B True True True ... True True True

In [15]:
extracted = ds.sel(latitude=xp.latitude,longitude=xp.longitude, method='nearest').to_dataframe()
extracted

                 reflectance   fwhm  good_wavelengths   latitude  longitude  \
Id  wavelengths
1   380.857880      0.020274  8.415               1.0  17.691368 -88.116043
    388.261475      0.020874  8.415               1.0  17.691368 -88.116043
    395.668091      0.021483  8.415               1.0  17.691368 -88.116043
    403.077698      0.022109  8.415               1.0  17.691368 -88.116043
    410.490265      0.023012  8.417               1.0  17.691368 -88.116043
...                      ...    ...               ...        ...        ...
113 2463.233887          NaN  8.803               1.0  16.815120 -88.164302
    2470.620117          NaN  8.804               1.0  16.815120 -88.164302
    2478.005371          NaN  8.806               1.0  16.815120 -88.164302
    2485.390869          NaN  8.807               1.0  16.815120 -88.164302
    2492.776123          NaN  8.809               1.0  16.815120 -88.164302

                     elev  spatial_ref
Id  wavelengths
1   380.857880  -6.412017            0
    388.261475  -6.412017            0
    395.668091  -6.412017            0
    403.077698  -6.412017            0
    410.490265  -6.412017            0
...                   ...          ...
113 2463.233887       NaN            0
    2470.620117       NaN            0
    2478.005371       NaN            0
    2485.390869       NaN            0
    2492.776123       NaN            0

[32205 rows x 7 columns]

In [16]:
filtered_df = extracted[extracted['good_wavelengths'] == 1]
#change file name to reflect a particular scene and CCN dataset
filtered_df.to_csv('C:/Users/campb/Documents/morrisette_out_20260125T172705.csv')

In [17]:
df = pd.read_csv('C:/Users/campb/Documents/morrisette_out_20260125T172705.csv')

In [18]:
# Data values are slightly different than -0.01 because of floating point precision, which requires a tolerance to be set
#1068 caye
#5875 lagoon
#3804 riverine
#df2 = df[df['Id']==1068]
df2 = df.loc[df['Id'].isin([1,7,100])]

#df2 = df({'Id': [200,300,400,500]})
df2['reflectance'] = df2['reflectance'].where(abs(df2['reflectance'] - (-0.01)) > 1e-8, np.nan)

df2

,Id,wavelengths,reflectance,fwhm,good_wavelengths,latitude,longitude,elev,spatial_ref
0,1,380.85788,0.020274,8.415,1.0,17.691368,-88.116043,-6.412017,0
1,1,388.26147,0.020874,8.415,1.0,17.691368,-88.116043,-6.412017,0
2,1,395.66810,0.021483,8.415,1.0,17.691368,-88.116043,-6.412017,0
3,1,403.07770,0.022109,8.415,1.0,17.691368,-88.116043,-6.412017,0
4,1,410.49026,0.023012,8.417,1.0,17.691368,-88.116043,-6.412017,0
...,...,...,...,...,...,...,...,...,...
25495,100,2463.23400,0.014251,8.803,1.0,17.287947,-87.816188,-7.032203,0
25496,100,2470.62000,0.015019,8.804,1.0,17.287947,-87.816188,-7.032203,0
25497,100,2478.00540,0.014578,8.806,1.0,17.287947,-87.816188,-7.032203,0
25498,100,2485.39090,0.014131,8.807,1.0,17.287947,-87.816188,-7.032203,0
25499,100,2492.77610,0.013690,8.809,1.0,17.287947,-87.816188,-7.032203,0

In [19]:
df2.hvplot(x='wavelengths',y='reflectance', by=['Id'], color=hv.Cycle('Dark2'), frame_height=400, frame_width=600).opts(title='Example Points - Reflectance', xlabel='Wavelengths (nm)',ylabel='Reflectance')

:NdOverlay   [Id]
   :Curve   [wavelengths]   (reflectance)