#Accessing and Downloading NISAR data

Install and import necessary libraries and mount to drive if using Google Colab

In [ ]:
!pip install earthaccess
!pip install xarray

Collecting earthaccess
  Downloading earthaccess-0.17.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: fsspec>=2025.2 in /usr/local/lib/python3.12/dist-packages (from earthaccess) (2025.3.0)
Requirement already satisfied: importlib-resources>=6.3.2 in /usr/local/lib/python3.12/dist-packages (from earthaccess) (6.5.2)
Collecting multimethod>=1.8 (from earthaccess)
  Downloading multimethod-2.0.2-py3-none-any.whl.metadata (8.4 kB)
Collecting pqdm>=0.1 (from earthaccess)
  Downloading pqdm-0.2.0-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting python-cmr>=0.10.0 (from earthaccess)
  Downloading python_cmr-0.13.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.12/dist-packages (from earthaccess) (2.32.4)
Collecting s3fs>=2025.2 (from earthaccess)
  Downloading s3fs-2026.3.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: tenacity>=8.0 in /usr/local/lib/python3.12/dist-packages (from earthaccess) (9.1.4)
Collecting tinynetrc>=1.3.1 (from earthaccess)
  Downloading tinynetrc-1.3.1-py2.py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from earthaccess) (4.15.0)
Collecting bounded-pool-executor (from pqdm>=0.1->earthaccess)
  Downloading bounded_pool_executor-0.0.3-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pqdm>=0.1->earthaccess) (4.67.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from python-cmr>=0.10.0->earthaccess) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26->earthaccess) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26->earthaccess) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26->earthaccess) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26->earthaccess) (2026.2.25)
Collecting aiobotocore<4.0.0,>=2.19.0 (from s3fs>=2025.2->earthaccess)
  Downloading aiobotocore-3.3.0-py3-none-any.whl.metadata (26 kB)
Collecting fsspec>=2025.2 (from earthaccess)
  Downloading fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from s3fs>=2025.2->earthaccess) (3.13.4)
Collecting aioitertools<1.0.0,>=0.5.1 (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2025.2->earthaccess)
  Downloading aioitertools-0.13.0-py3-none-any.whl.metadata (3.3 kB)
Collecting botocore<1.42.71,>=1.42.62 (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2025.2->earthaccess)
  Downloading botocore-1.42.70-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2025.2->earthaccess)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2025.2->earthaccess) (6.7.1)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs>=2025.2->earthaccess) (2.1.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2025.2->earthaccess) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2025.2->earthaccess) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2025.2->earthaccess) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2025.2->earthaccess) (1.8.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2025.2->earthaccess) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs>=2025.2->earthaccess) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->python-cmr>=0.10.0->earthaccess) (1.17.0)
Downloading earthaccess-0.17.0-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 2.1 MB/s eta 0:00:00
Downloading multimethod-2.0.2-py3-none-any.whl (9.6 kB)
Downloading pqdm-0.2.0-py2.py3-none-any.whl (6.8 kB)
Downloading python_cmr-0.13.0-py3-none-any.whl (14 kB)
Downloading s3fs-2026.3.0-py3-none-any.whl (32 kB)
Downloading fsspec-2026.3.0-py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.6/202.6 kB 5.3 MB/s eta 0:00:00
Downloading tinynetrc-1.3.1-py2.py3-none-any.whl (3.9 kB)
Downloading aiobotocore-3.3.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.8/87.8 kB 8.4 MB/s eta 0:00:00
Downloading bounded_pool_executor-0.0.3-py3-none-any.whl (3.4 kB)
Downloading aioitertools-0.13.0-py3-none-any.whl (24 kB)
Downloading botocore-1.42.70-py3-none-any.whl (14.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 74.9 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: tinynetrc, bounded-pool-executor, pqdm, multimethod, jmespath, fsspec, aioitertools, python-cmr, botocore, aiobotocore, s3fs, earthaccess
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2026.3.0 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.3.0 which is incompatible.
Successfully installed aiobotocore-3.3.0 aioitertools-0.13.0 botocore-1.42.70 bounded-pool-executor-0.0.3 earthaccess-0.17.0 fsspec-2026.3.0 jmespath-1.1.0 multimethod-2.0.2 pqdm-0.2.0 python-cmr-0.13.0 s3fs-2026.3.0 tinynetrc-1.3.1
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (2025.12.0)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from xarray) (2.0.2)
Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.12/dist-packages (from xarray) (26.0)
Requirement already satisfied: pandas>=2.2 in /usr/local/lib/python3.12/dist-packages (from xarray) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->xarray) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->xarray) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2->xarray) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2->xarray) (1.17.0)

In [ ]:
!pip install rioxarray

In [4]:
import earthaccess
import rioxarray
import xarray as xr
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
import os
import pyproj
from shapely.ops import transform
from shapely.geometry import Point

/opt/anaconda3/envs/bkos/lib/python3.14/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.0.1)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Define search parameters
For this example, `'NISAR_L2_GCOV_BETA_V1'` Level 2 GCOV data is chosen based on recommended dataset for AGB. To select a different dataset, change the `short_name` variable to a different dataset link.

First, we extract unique coordinate values (longitude, latitude) from a CSV file.

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/AGB_MERGED.csv')

In [ ]:
# get unique longitude and latitude values in df
unique_coordinates = df[['longitude', 'latitude']].drop_duplicates()
unique_coordinates.head()

     longitude   latitude
0   -88.604370  13.227360
87  -88.329576  13.187182
133 -88.336737  13.199314
176 -88.328149  13.202545
255 -88.777010  13.249280

In [ ]:
# convert unique coordinates to input list
coordinates = unique_coordinates.values.tolist()
coordinates

[[-88.60436965931343, 13.227360376425882],
 [-88.32957619089184, 13.18718236595375],
 [-88.33673736866605, 13.199313945612474],
 [-88.32814867984379, 13.202544595221848],
 [-88.77701022951307, 13.249280282257898],
 [-88.78627945640167, 13.253780866694571],
 [-88.45847120700725, 13.216425037256805],
 [-88.45282895239485, 13.222649375363313],
 [-88.39708878488749, 13.192148089259586],
 [-88.5611707304826, 13.25777524858816],
 [-88.56947923249115, 13.240579840183145],
 [-88.81947537256227, 13.25838852729372],
 [-88.829697438107, 13.26988873318014],
 [-88.85941098322873, 13.290139029224513],
 [-88.87336361287223, 13.2969725586972],
 [-88.8811135458455, 13.306055966759253],
 [-88.94430740618901, 13.334139958571113],
 [-88.82980837402025, 13.286222168279906],
 [-88.95555744426943, 13.32530666005413],
 [-88.85333616230449, 13.270388924217926],
 [-88.89086322384209, 13.342278442231413],
 [-88.82673, 13.25972],
 [-88.92136, 13.3442],
 [-88.85316944551337, 13.280111192559334],
 [-88.8590027250846, 13.28238898769338],
 [-88.76582299434297, 13.271776794497368],
 [-82.2813, 8.30711],
 [-82.4404, 8.31786],
 [-82.4212, 8.33466],
 [-82.3656, 8.30401],
 [-82.4038, 8.31768],
 [-82.3499, 8.27676],
 [-82.4348, 8.33622],
 [-85.24869036819523, 10.25298477595526],
 [-85.24854438327802, 10.25315845728881],
 [-85.24839839820515, 10.25333213857375],
 [-85.24825241297667, 10.253505819810066],
 [-85.24810642759255, 10.253679500997768],
 [-85.24796044205277, 10.253853182136838],
 [-85.1463881303272, 10.165461146801222],
 [-85.14582616538885, 10.165074225524112],
 [-85.14563884403096, 10.16494525151594],
 [-85.14545152281717, 10.164816277383206],
 [-85.07769105553321, 10.142826427036614],
 [-85.07771018303961, 10.142601217440228],
 [-85.07772931053574, 10.142376007842453],
 [-85.07774843802156, 10.142150798243296],
 [-85.07776756549706, 10.141925588642758],
 [-85.07778669296225, 10.14170037904084],
 [-85.14926495060175, 10.10645927214201],
 [-85.14909075376282, 10.106605151259586],
 [-85.14891655676377, 10.10675103030112],
 [-85.1487423596046, 10.10689690926662],
 [-85.14856816228534, 10.107042788156075],
 [-85.14839396480595, 10.107188666969485],
 [-85.1276758818348, 10.101113622249434],
 [-85.12759861748444, 10.101326260723056],
 [-85.12752135304598, 10.101538899186892],
 [-85.12744408851938, 10.10175153764094],
 [-85.12736682390468, 10.101964176085204],
 [-85.12728955920186, 10.102176814519666],
 [-85.24459889402941, 10.13380450121516],
 [-85.2446376413812, 10.133581793447371],
 [-85.2446763886976, 10.133359085678466],
 [-85.24471513597861, 10.133136377908418],
 [-85.24475388322423, 10.13291367013725],
 [-85.2447926304345, 10.132690962364958],
 [-85.11858458886034, 9.97441122528924],
 [-85.11863512207638, 9.974190842238896],
 [-85.11868565524009, 9.973970459185455],
 [-85.11873618835142, 9.973750076128928],
 [-85.11878672141042, 9.97352969306931],
 [-85.11883725441706, 9.973309310006597],
 [-85.03930615174993, 9.963613050433567],
 [-85.03945214609286, 9.963439460891797],
 [-85.03959814028423, 9.963265871300102],
 [-85.03974413432404, 9.96309228165848],
 [-85.03989012821232, 9.962918691966944],
 [-85.04003612194903, 9.96274510222548],
 [-85.19361632213443, 10.175289078351582],
 [-85.19353909080297, 10.17550172853886],
 [-85.19346185938346, 10.175714378716856],
 [-85.19338462787589, 10.175927028885578],
 [-85.19330739628028, 10.17613967904501],
 [-85.19323016459659, 10.176352329195169],
 [-84.92116969256782, 9.827494909790346],
 [-84.9212998948107, 9.827309409593571],
 [-84.92143009691338, 9.82712390935795],
 [-84.92156029887592, 9.826938409083484],
 [-84.92169050069826, 9.826752908770167],
 [-84.92182070238043, 9.826567408418011],
 [-84.81729020897713, 9.986094181123526],
 [-84.81714407907403, 9.98626768471754],
 [-84.81699794901832, 9.986441188258013],
 [-84.81685181881002, 9.98661469174494],
 [-84.8167056884491, 9.98678819517832],
 [-84.81655955793559, 9.986961698558147],
 [-84.85541067678167, 10.00067647047107],
 [-84.85531484815563, 10.000881562957687],
 [-84.85521901941794, 10.001086655424212],
 [-84.85512319056856, 10.001291747870647],
 [-84.85502736160753, 10.001496840296978],
 [-84.85493153253478, 10.001701932703211],
 [-85.20072386609274, 10.084275038114814],
 [-85.20083716691438, 10.08407890552643],
 [-85.20075838203638, 10.083866823032125],
 [-85.20067959727562, 10.083654740504434],
 [-85.20060081263208, 10.083442657943348],
 [-85.20052202810575, 10.083230575348871],
 [-85.18687241094233, 10.065342715542222],
 [-85.18674093636079, 10.06515805920538],
 [-85.18660946193494, 10.064973402797118],
 [-85.18647798766473, 10.064788746317443],
 [-85.18634651355016, 10.064604089766354],
 [-85.18621503959126, 10.06441943314386],
 [-83.56307209270106, 8.89365660538488],
 [-83.56297116981206, 8.89357754892092],
 [-83.56299762113586, 8.838085568384567],
 [-83.56291916866067, 8.838546086832654],
 [-83.59114347881065, 8.801477038795538],
 [-83.56290671179939, 8.838316309936266],
 [-83.5629253891326, 8.838744932126428],
 [-83.5628989567528, 8.83903452309212],
 [-83.56334297998077, 8.893866158652385],
 [-83.56355311914639, 8.894008276418745],
 [-83.56318618257102, 8.893750054308114],
 [-83.59088325213587, 8.801868466635483],
 [-83.59088700101017, 8.802096968412602],
 [-83.59116677984736, 8.801283740725523],
 [-83.59101864339385, 8.801667694810963],
 [-83.60836840399742, 8.933191030180224],
 [-83.60775288108016, 8.932925172602515],
 [-83.60756086845812, 8.932802266995363],
 [-83.60807600984076, 8.932973347041777],
 [-83.60819776498252, 8.933063988014691],
 [-88.424776, 16.510383],
 [-88.424687, 16.510577],
 [-88.424582, 16.51077],
 [-88.424456, 16.510987],
 [-88.424355, 16.51119],
 [-88.424259, 16.511387],
 [-88.16455, 16.644835],
 [-88.164332, 16.644791],
 [-88.164128, 16.644709],
 [-88.163938, 16.644587],
 [-88.163719, 16.644532],
 [-88.163687, 16.644742],
 [-88.062677, 17.491791],
 [-88.062985, 17.491817],
 [-88.063197, 17.491855],
 [-88.063451, 17.491839],
 [-88.063657, 17.491837],
 [-88.063859, 17.49182],
 [-88.6565, 16.18206],
 [-88.656372, 16.182147],
 [-88.65619, 16.18223],
 [-88.65605, 16.182337],
 [-88.65589, 16.182404],
 [-88.6557, 16.18248],
 [-88.242735, 16.938988],
 [-88.242891, 16.93908],
 [-88.243067, 16.939103],
 [-88.243254, 16.939055],
 [-88.243414, 16.939034],
 [-88.243595, 16.939019],
 [-88.11592, 17.691465],
 [-88.116119, 17.691475],
 [-88.116355, 17.691509],
 [-88.116596, 17.691458],
 [-88.116795, 17.691358],
 [-88.117022, 17.691317],
 [-88.392519, 18.337675],
 [-88.387317, 18.341508],
 [-88.384435, 18.340982],
 [-88.384322, 18.340789],
 [-88.385284, 18.34228],
 [-88.591185, 16.288337],
 [-88.591221, 16.288585],
 [-88.5913, 16.28884],
 [-88.591352, 16.289035],
 [-88.591436, 16.28924],
 [-88.591477, 16.289436],
 [-88.106667, 18.339157],
 [-88.106869, 18.339243],
 [-88.107092, 18.339325],
 [-88.107297, 18.339418],
 [-88.107522, 18.339505],
 [-88.107774, 18.339577],
 [-87.81233, 17.28646],
 [-87.81233, 17.28622],
 [-87.81233, 17.286],
 [-87.81232, 17.28576],
 [-87.81233, 17.28556],
 [-87.8123, 17.28534],
 [-81.80876922607422, 8.155683517456055],
 [-87.57265371130879, 15.80189709349495],
 [-87.56786757793881, 15.796539775146195],
 [-87.58380346450866, 15.776301779539615],
 [-87.58369710062313, 15.781545377557842],
 [-87.59750846723803, 15.82407797559854],
 [-87.59092924582154, 15.81904254565269],
 [-87.63939111997114, 15.904722378016762],
 [-87.63424061919928, 15.885789665206715],
 [-87.63362735194197, 15.880846562685884],
 [-87.63041998453517, 15.90670138695002],
 [-87.60076763272538, 15.855736519811511],
 [-87.60578922236901, 15.86098387343719],
 [-46.679316666666665, -0.9180333333333334],
 [-46.67918333333333, -0.9181],
 [-46.67901666666667, -0.9182833333333332],
 [-46.67895, -0.9183333333333332],
 [-46.67885, -0.91855],
 [-46.67876666666667, -0.9187],
 [-46.6523, -0.8812166666666666],
 [-46.65238333333333, -0.8813666666666666],
 [-46.65245, -0.8815833333333334],
 [-46.652483333333336, -0.8817333333333334],
 [-46.6525, -0.8819333333333332],
 [-46.652566666666665, -0.8821],
 [-40.031406, -2.849978],
 [-40.0315, -2.84983],
 [-40.031711, -2.849504],
 [-40.031187, -2.850264],
 [-40.03127, -2.850129],
 [-40.031545, -2.849697],
 [-47.39423333333333, -0.6549333333333334],
 [-47.39423333333333, -0.65515],
 [-47.3943, -0.6553166666666667],
 [-47.3942, -0.65555],
 [-47.39416666666666, -0.6556833333333334],
 [-47.394133333333336, -0.6558666666666666],
 [-40.133954, -2.8441],
 [-40.133857, -2.843972],
 [-40.133709, -2.843674],
 [-40.133586, -2.843491],
 [-40.133455, -2.843392],
 [-40.133742, -2.843821],
 [-46.63706666666667, -0.8511666666666666],
 [-46.6372, -0.8510500000000001],
 [-46.63735, -0.85095],
 [-46.6375, -0.85085],
 [-46.6376, -0.8507333333333332],
 [-46.637816666666666, -0.8506],
 [-47.35113333333334, -0.6555833333333333],
 [-47.35098333333333, -0.6554666666666668],
 [-47.350966666666665, -0.6552833333333333],
 [-47.35086666666667, -0.65515],
 [-47.35075, -0.6550333333333334],
 [-47.35066666666667, -0.6548666666666667],
 [-47.3674, -0.6325333333333333],
 [-47.3674, -0.6327333333333333],
 [-47.36748333333333, -0.6328666666666667],
 [-47.36753333333333, -0.6330666666666667],
 [-47.367583333333336, -0.6331833333333333],
 [-47.36765, -0.63345],
 [-46.6386, -0.8413333333333333],
 [-46.63861666666666, -0.84135],
 [-46.63863333333333, -0.8413666666666667],
 [-46.63865, -0.8413833333333333],
 [-46.638666666666666, -0.8414],
 [-46.63868333333333, -0.8414166666666667],
 [-46.6387, -0.8414333333333333],
 [-46.63871666666667, -0.84145],
 [-46.63873333333333, -0.8414666666666667],
 [-46.63875, -0.8414833333333332],
 [-46.64008333333334, -0.8419500000000001],
 [-46.6401, -0.8419666666666666],
 [-46.64011666666666, -0.8419833333333333],
 [-46.64013333333333, -0.8420000000000001],
 [-46.64015, -0.8420166666666666],
 [-46.640166666666666, -0.8420333333333333],
 [-46.64018333333333, -0.8420500000000001],
 [-46.6402, -0.8420666666666666],
 [-46.64021666666667, -0.8420833333333333],
 [-46.640233333333335, -0.8421000000000001],
 [-46.64025, -0.8421166666666667],
 [-46.64026666666667, -0.8421333333333333],
 [-46.640283333333336, -0.8421500000000001],
 [-46.6403, -0.8421666666666667],
 [-46.64031666666666, -0.8421833333333333],
 [-46.64033333333333, -0.8422],
 [-46.64035, -0.8422166666666667],
 [-46.640366666666665, -0.8422333333333333],
 [-46.64038333333333, -0.8422499999999999],
 [-46.6404, -0.8422666666666667],
 [-46.64041666666667, -0.8422833333333333],
 [-46.64043333333333, -0.8422999999999999],
 [-46.64045, -0.8423166666666667],
 [-46.64046666666667, -0.8423333333333333],
 [-46.640483333333336, -0.8423499999999999],
 [-46.6405, -0.8423666666666667],
 [-46.64051666666667, -0.8423833333333334],
 [-46.64053333333333, -0.8423999999999999],
 [-46.64055, -0.8424166666666667],
 [-46.640566666666665, -0.8424333333333334],
 [-46.64058333333333, -0.8424499999999999],
 [-46.6406, -0.8424666666666667],
 [-46.640616666666666, -0.8424833333333334],
 [-46.64063333333333, -0.8424999999999999],
 [-46.64065, -0.8425166666666667],
 [-46.64066666666667, -0.8425333333333334],
 [-46.640683333333335, -0.8425499999999999],
 [-46.6407, -0.8425666666666667],
 [-46.64071666666667, -0.8425833333333334],
 [-46.64073333333333, -0.8425999999999999],
 [-46.64075, -0.8426166666666667],
 [-46.64076666666666, -0.8426333333333333],
 [-48.01373333333333, -0.74915],
 [-48.01361666666666, -0.7493333333333333],
 [-48.01355, -0.7494833333333334],
 [-48.013333333333335, -0.7495666666666666],
 [-48.013216666666665, -0.7497333333333334],
 [-48.0131, -0.7498166666666666]]

Define search range for NISAR data:

*   `short_name` = name of dataset from NASA Earthdata catalogue
*   `time range` = time range to search for granules
*   `buffer` = buffer in meters around each coordinate. Used to create polygon for each coordinate.
* `count` = number of results to return for each coordinate search

In [ ]:
## USER DEFINED VARIABLES ##
short_name = 'NISAR_L2_GCOV_BETA_V1'
time_range = ('2025-12-01', '2026-03-01')
buffer = 0.001 # 100 meter buffer around each point
count = 1 #limit the search to top 10 results

### Authenticate with Earthdata

Log in to NASA Earthdata with your username and password. This is necessary to access and download the NISAR data.

In [ ]:
earthaccess.login()

### Search for NISAR Granules

First, we iterate through the provided coordinates, create a bounding box (polygon based on the defined buffer) for each coordinate, and then use `earthaccess.search_data` to find relevant NISAR granules with our previously defined search parameters.

The results are then opened and stored in `granules` to make the data accessible for further processing.

In [ ]:
# create buffer polygons for each coordinates and search for data
results = []
for lon, lat in coordinates:

    point_bbox = (lon - buffer, lat - buffer, lon + buffer, lat + buffer)
    result = earthaccess.search_data(
        short_name=short_name,
        temporal=time_range,
        bounding_box=point_bbox,
        cloud_hosted=True,
        count=count
    )
    results.extend(result)

In [ ]:
granules = earthaccess.open(results)

/usr/local/lib/python3.12/dist-packages/earthaccess/store.py:516: FutureWarning: As of version 1.0, `DataGranule.size` will be accessed as an attribute; e.g. use `DataCollection.size` **not** `DataCollection.size()`
  total_size = round(sum([granule.size() for granule in granules]) / 1024, 2)

QUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]

PROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]

COLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
granules

### Extract and Process Data from Granules

This loop iterates through each opened granule, extracts its metadata (including the `date`), and then processes the data for each coordinate:

1.  **Coordinate Transformation**: Renames coordinates to standard `x`/`y` format and transforms (longitude, latitude) to native Coordinate Reference System (CRS) of NISAR data.
2.  **Value Extraction**: If the coordinate is within bounds, we extract the `HHHH` and `HVHV` polarization values via `method='nearest'` to find the closest data point.
3.  **Data Aggregation**: The extracted date, coordinates, and NISAR values are appended to a list (`all_data`).

Finally, a pandas DataFrame `df` is created from `all_data` and its head is displayed.

In [ ]:
all_data = []

for i, f in enumerate(granules):
    #get metadata and date
    with xr.open_dataset(f, engine='h5netcdf', group='science/LSAR/GCOV/grids/frequencyA',backend_kwargs={'phony_dims': 'sort'}) as ds:

        # conver to correct coordinates to epsg format
        ds = ds.rename({'xCoordinates': 'x', 'yCoordinates': 'y'})

        # conver to native NISAR format
        native_crs = f"EPSG:{ds.projection.epsg_code}"
        ds = ds.rio.write_crs(native_crs)
        transformer = pyproj.Transformer.from_crs("EPSG:4326", native_crs, always_xy=True)

        # get time
        granule_metadata = results[i]["umm"]
        granule_date = granule_metadata['TemporalExtent']['RangeDateTime']['BeginningDateTime']


        for lon, lat in coordinates:
            target_x, target_y = transformer.transform(lon, lat)

            # access data for coordinates only
            if (ds.x.min() <= target_x <= ds.x.max()) and (ds.y.min() <= target_y <= ds.y.max()):
                try:

                    val_hhhh = ds['HHHH'].sel(x=target_x, y=target_y, method='nearest').values.item()
                    val_hvhv = ds['HVHV'].sel(x=target_x, y=target_y, method='nearest').values.item()



                    all_data.append({
                        'date': granule_date,
                        'longitude': lon,
                        'latitude': lat,
                        'nisar_value_hvhv': val_hvhv,
                        'nisar_value_hhhh': val_hhhh
                    })
                except Exception as e:
                    print(f"Point ({lon}, {lat}) not in granule {i}: {e}")

# create df and preview
df = pd.DataFrame(all_data)
df.head()

,date,longitude,latitude,nisar_value_hvhv,nisar_value_hhhh
0,2025-12-13T11:30:58.000000Z,-88.604370,13.227360,0.022314,0.109666
1,2025-12-13T11:30:58.000000Z,-88.329576,13.187182,NaN,NaN
2,2025-12-13T11:30:58.000000Z,-88.336737,13.199314,NaN,NaN
3,2025-12-13T11:30:58.000000Z,-88.328149,13.202545,NaN,NaN
4,2025-12-13T11:30:58.000000Z,-88.777010,13.249280,0.028810,0.045714

In [ ]:
# sort df by longitude
df = df.sort_values(by='longitude', ascending=False)
df

### Identify and Remove Missing Data

Next, we inspect the DataFrame `df` to ensure that only complete data entries are kept for further analysis. We filter the DataFrame `df` to show rows that contain any missing values, and remove all rows that contain any `NaN` values. The cleaned DataFrame is then displayed.

In [ ]:
df_nan = df[df.isna().any(axis=1)]
df_nan.head()

,date,longitude,latitude,nisar_value_hvhv,nisar_value_hhhh
1,2025-12-13T11:30:58.000000Z,-88.329576,13.187182,NaN,NaN
2,2025-12-13T11:30:58.000000Z,-88.336737,13.199314,NaN,NaN
3,2025-12-13T11:30:58.000000Z,-88.328149,13.202545,NaN,NaN

In [ ]:
# drop nulls
df = df.dropna()
df

,date,longitude,latitude,nisar_value_hvhv,nisar_value_hhhh
0,2025-12-13T11:30:58.000000Z,-88.604370,13.227360,0.022314,0.109666
4,2025-12-13T11:30:58.000000Z,-88.777010,13.249280,0.028810,0.045714
5,2025-12-13T11:30:58.000000Z,-88.786279,13.253781,0.020070,0.071964
6,2025-12-13T11:30:58.000000Z,-88.458471,13.216425,0.020845,0.027211
7,2025-12-13T11:30:58.000000Z,-88.452829,13.222649,0.000495,0.001906
...,...,...,...,...,...
121,2025-12-13T11:30:58.000000Z,-48.013617,-0.749333,0.031607,0.086866
122,2025-12-13T11:30:58.000000Z,-48.013550,-0.749483,0.035105,0.149189
123,2025-12-13T11:30:58.000000Z,-48.013333,-0.749567,0.035268,0.157301
124,2025-12-13T11:30:58.000000Z,-48.013217,-0.749733,0.060446,0.210852
125,2025-12-13T11:30:58.000000Z,-48.013100,-0.749817,0.014924,0.109516

### Save Extracted NISAR Data and Coordinates to CSV

The final step is saving the processed and cleaned NISAR data (stored in `df`) to a CSV file in a directory of your choosing (we used Google Drive).

Extracted coordinates (stored in `df_coord`) are also saved to a CSV file (`nisar_coordinates.csv`).

In [ ]:
# save df to csv
filename = "/content/drive/MyDrive/nisar_data.csv"
df.to_csv(filename, index=False)
print(f"Download complete. NISAR data saved to {filename}.")

Download complete. NISAR data saved to /content/drive/MyDrive/nisar_data.csv.

In [ ]:
# save coordinates to csv
df_coord = df[['longitude', 'latitude']]
df_coord.head()

   longitude   latitude
0 -88.604370  13.227360
4 -88.777010  13.249280
5 -88.786279  13.253781
6 -88.458471  13.216425
7 -88.452829  13.222649

In [ ]:
filename = "/content/drive/MyDrive/nisar_coordinates.csv"
df_coord.to_csv(filename, index=False)
print(f"Download complete. NISAR coordinates saved to {filename}.")

Download complete. NISAR coordinates saved to /content/drive/MyDrive/nisar_coordinates.csv.

# Main Function

In [ ]:
if __name__ == "__main__":
    results = []
    for lon, lat in coordinates:

        point_bbox = (lon - buffer, lat - buffer, lon + buffer, lat + buffer)
        result = earthaccess.search_data(
            short_name=short_name,
            temporal=time_range,
            bounding_box=point_bbox,
            cloud_hosted=True,
            count=10
        )
        results.extend(result)
    granules = earthaccess.open(results)
    all_data = []

    for i, f in enumerate(granules):
        # get metadata and date
        with xr.open_dataset(f,
                             engine='h5netcdf',
                             group='science/LSAR/GCOV/grids/frequencyA',
                             backend_kwargs={'phony_dims': 'sort'}) as ds:

            # conver to correct coordinates to epsg format
            ds = ds.rename({'xCoordinates': 'x', 'yCoordinates': 'y'})

            # convert to native NISAR format
            native_crs = f"EPSG:{ds.projection.epsg_code}"
            ds = ds.rio.write_crs(native_crs)
            transformer = pyproj.Transformer.from_crs("EPSG:4326", native_crs, always_xy=True)

            # get time
            granule_metadata = results[i]["umm"]
            granule_date = granule_metadata['TemporalExtent']['RangeDateTime']['BeginningDateTime']


            for lon, lat in coordinates:
                target_x, target_y = transformer.transform(lon, lat)

                # access data for coordinates only
                if (ds.x.min() <= target_x <= ds.x.max()) and (ds.y.min() <= target_y <= ds.y.max()):
                    try:
                        # extracting HHHH and HVHV data elements, but more/differet data can be added here
                        val_hhhh = ds['HHHH'].sel(x=target_x, y=target_y, method='nearest').values.item()
                        val_hvhv = ds['HVHV'].sel(x=target_x, y=target_y, method='nearest').values.item()
                        
                        all_data.append({
                            'date': granule_date,
                            'longitude': lon,
                            'latitude': lat,
                            'nisar_value_hvhv': val_hv,
                            'nisar_value_hhhh': val_hh
                        })
                    except Exception as e:
                        print(f"Point ({lon}, {lat}) not in granule {i}: {e}")

    # create df and save to csv
    df = pd.DataFrame(all_data)
    df.to_csv("nisar_extracted_values.csv", index=False)
    print("Download complete. NISAR data saved to 'nisar_extracted_values.csv'.")

# MERGE NISAR PARAMETERS WITH AGB DATA

In [26]:
NISAR_DATA_CSV = "../../../DATA/AGB_DATA/Merged_Data/NISAR/nisar_data.csv"
nisar_df = pd.read_csv(NISAR_DATA_CSV)
nisar_df.columns

Index(['date', 'longitude', 'latitude', 'nisar_value_hvhv',
       'nisar_value_hhhh'],
      dtype='object')

In [27]:
nisar_df.shape

(123, 5)

In [28]:
AGB_INPUT_CSV  = "../../../DATA/AGB_DATA/Merged_Data/AGB_MERGED.csv"
agb_df = pd.read_csv(AGB_INPUT_CSV)
agb_df.columns

Index(['dataset', 'plot_id', 'start_date', 'end_date', 'latitude', 'longitude',
       'diameter', 'height', 'species', 'plant_AGB_kg'],
      dtype='object')

In [29]:
agb_df.shape

(8774, 10)

## Merge data

In [31]:
# Keep only AGB rows whose coordinates exist in NISAR
filtered_agb_df = agb_df.merge(nisar_df, on=['longitude', 'latitude'], how='inner')

In [32]:
print(f"Original AGB rows:  {len(agb_df)}")
print(f"Filtered AGB rows:  {len(filtered_agb_df)}")
print(filtered_agb_df.columns)

Original AGB rows:  8774
Filtered AGB rows:  3176
Index(['dataset', 'plot_id', 'start_date', 'end_date', 'latitude', 'longitude',
       'diameter', 'height', 'species', 'plant_AGB_kg', 'date',
       'nisar_value_hvhv', 'nisar_value_hhhh'],
      dtype='object')

## SAVE TO FILE

In [33]:
AGB_OUTPUT_CSV = "../../../DATA/AGB_DATA/Merged_Data/NISAR/Nisar_AGB.csv"
filtered_agb_df.to_csv(AGB_OUTPUT_CSV, index=False)